description: Just another documentation theme compatible with GitHub Pages

# debug:
#   dist: false
#   compress: true
#   shortcodes: true

lsi: false
theme: null
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
readme_index:
  with_frontmatter: true

exclude:
  - CNAME
  - LICENSE
  - Gemfile
  - Gemfile_
  - Makefile
  - keras.json
  - update.sh
  - action.yml  
  - Dockerfile
  - Gemfile.lock
  - node_modules
  - package.json
  - entrypoint.sh
  - entrypoint.sh_
  - pinned_repos.rb
  - requirements.txt
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
  - jekyll-rtd-theme.gemspec_

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
