description: Mapping the quantum way across prime identity

# debug:
#   dist: false
#   compress: true
#   shortcodes: true

lsi: false
title: ₠Quantum
incremental: false
highlighter: rouge

source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : /maps/_plugins/gems # takes an array of strings and loads plugins in that order
layouts_dir         : /maps/_layouts
data_dir            : /maps/_data
includes_dir        : /maps/_includes
sass:
  sass_dir: /maps/_sass
collections:
  posts:
    output          : true

gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# folders sort
readme_index:
  with_frontmatter: true

exclude:
  - LICENSE
  - action.yml  
  - Dockerfile

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
