description: Theme compatible with GitHub Pages

# debug:
#   dist: false
#   compress: true
#   shortcodes: true

lsi: false
safe: true
source: .
theme: null
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
  
plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
