name: Docker Deploy Action

description: >
  🪂  A Github Action to deploy pages

branding:
  icon: 'command'
  color: 'yellow'

inputs:
  docker_hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}
    required: false
  docker_hub_password:
    description: Docker Hub password
    required: true
  docker_hub_token:
    description: Docker Hub authentication token
    required: true
  initiate_pauli_sum:
    description: Build args
    required: false
    default: ""
  image_name:
    description: Tag to use for the new image
    default: ${{ github.action_repository }}
    required: true
  credentials:
    description: The Google cloud credentials
    required: true
  token:
    description: The Github personal token
    required: true
  base:
    description: The path to .github folder
    required: true
  id:
    description: The id according to os
    required: true

outputs:
  addition:
    description: Collect addition outputs
    value: ${{ inputs.id == 1 && steps.addition.outputs.artifact }}
  multiplication:
    description: Collect multiplication outputs
    value: ${{ toJSON(steps.multiplication.outputs) }}

runs:
  using: composite
  steps:
    - name: Target Configuration
      uses: eq19/eq19/.github/actions/1-addition/2-feed@v1
      if: inputs.id == 1
      id: addition
      with:
        hub_username: ${{ inputs.docker_hub_username }}
        hub_password: ${{ inputs.docker_hub_password }}
        hub_token: ${{ inputs.docker_hub_token }}
        credentials: ${{ inputs.credentials }}
        action_path: ${{ github.action_path }}
        image_name: ${{ inputs.image_name }}
        token: ${{ inputs.token }}

    - name: Profiling Feedback
      uses: eq19/eq19/.github/actions/2-multiplication/2-feed@v1
      if: inputs.id == 2
      id: multiplication
      with:
        token: ${{ inputs.token }}
        image_name: ${{ inputs.image_name }}
        action_path: ${{ github.action_path }}
        hub_token: ${{ inputs.docker_hub_token }} 
        hub_username: ${{ inputs.docker_hub_username }}
